### Validation with Hamburg Network

In [1]:
import geopandas as gpd

hamburg_db_raw_gdf = gpd.GeoDataFrame(gpd.read_file("db_rad_plus_json/de_hh_up_jahr2025_EPSG_4326.json").rename(
    columns={"anzahl": "count", "geometry": "geom"}), crs=4326, geometry="geom")
hamburg_db_raw_gdf

,id,count,geschwindigkeit,von,bis,strichbreite,geom
0,DE.HH.UP_JAHR2025_1,9,15.8,2025-01-01,2025-12-31,0.1,"LINESTRING (10.05301 53.57511, 10.05304 53.57517)"
1,DE.HH.UP_JAHR2025_2,9,18.9,2025-01-01,2025-12-31,0.1,"LINESTRING (10.03946 53.53272, 10.0395 53.53276)"
2,DE.HH.UP_JAHR2025_3,9,25.2,2025-01-01,2025-12-31,0.1,"LINESTRING (10.06909 53.58108, 10.06922 53.58103)"
3,DE.HH.UP_JAHR2025_4,9,14.4,2025-01-01,2025-12-31,0.1,"LINESTRING (9.91067 53.45982, 9.91222 53.45855)"
4,DE.HH.UP_JAHR2025_5,9,16.9,2025-01-01,2025-12-31,0.1,"LINESTRING (10.041 53.5354, 10.04097 53.53536)"
...,...,...,...,...,...,...,...
156581,DE.HH.UP_JAHR2025_156582,6214,20.7,2025-01-01,2025-12-31,5.7,"LINESTRING (10.00218 53.55744, 9.99902 53.55756)"
156582,DE.HH.UP_JAHR2025_156583,6317,19.5,2025-01-01,2025-12-31,5.8,"LINESTRING (9.99902 53.55756, 9.99854 53.55768)"
156583,DE.HH.UP_JAHR2025_156584,6357,18.9,2025-01-01,2025-12-31,5.8,"LINESTRING (9.99746 53.55795, 9.99698 53.55809)"
156584,DE.HH.UP_JAHR2025_156585,6401,19.2,2025-01-01,2025-12-31,5.8,"LINESTRING (9.99854 53.55768, 9.99746 53.55795)"
156585,DE.HH.UP_JAHR2025_156586,6653,19.7,2025-01-01,2025-12-31,6.0,"LINESTRING (10.00379 53.55752, 10.00218 53.55744)"

In [3]:
import os
from sqlalchemy import create_engine
db_url = (
    f"postgresql://{os.getenv('POSTGRES_USER')}:"
    f"{os.getenv('POSTGRES_PASSWORD')}@"
    f"localhost:5432/"
    f"{os.getenv('POSTGRES_DB')}"
)

engine = create_engine(db_url)

In [4]:
hamburg_db_raw_gdf.to_postgis("hamburg_db_rad_2025_raw", engine, if_exists="replace")

### Stadtradeln Dataset

In [5]:
import geopandas as gpd

hamburg_sr_raw_gdf = gpd.GeoDataFrame(gpd.read_file("stadtradeln_json/de_hh_up_stadtradeln2019_EPSG_4326.json").rename(
    columns= {"anzahl":"count", "geometry":"geom"}), geometry="geom")
hamburg_sr_raw_gdf

,id,count,anzahl_in,geschwindigkeit_in,anzahl_gegen,geschwindigkeit_gegen,strichstaerke,geom
0,DE.HH.UP_STADTRADELN2019_308318,10,6,18.7,4.0,19.5,0.229621,"LINESTRING (10.13175 53.57264, 10.13218 53.57264)"
1,DE.HH.UP_STADTRADELN2019_307179,25,18,17.2,7.0,15.2,0.436083,"LINESTRING (10.14791 53.56997, 10.14786 53.56998)"
2,DE.HH.UP_STADTRADELN2019_307489,20,14,20.7,6.0,17.4,0.373020,"LINESTRING (10.13876 53.56415, 10.1386 53.564)"
3,DE.HH.UP_STADTRADELN2019_307493,20,6,17.7,14.0,21.4,0.373020,"LINESTRING (10.13876 53.56415, 10.13899 53.56428)"
4,DE.HH.UP_STADTRADELN2019_307499,19,10,12.8,9.0,15.7,0.359864,"LINESTRING (10.13674 53.56302, 10.13279 53.56332)"
...,...,...,...,...,...,...,...,...
235235,DE.HH.UP_STADTRADELN2019_305899,1,1,19.7,NaN,NaN,0.045815,"LINESTRING (10.12571 53.57712, 10.12583 53.57721)"
235236,DE.HH.UP_STADTRADELN2019_305948,2,2,14.4,NaN,NaN,0.074427,"LINESTRING (10.12951 53.57585, 10.13019 53.57732)"
235237,DE.HH.UP_STADTRADELN2019_305950,1,1,16.0,NaN,NaN,0.045815,"LINESTRING (10.13019 53.57732, 10.13024 53.57741)"
235238,DE.HH.UP_STADTRADELN2019_306993,1,1,13.5,NaN,NaN,0.045815,"LINESTRING (10.14248 53.5701, 10.14248 53.57014)"
235239,DE.HH.UP_STADTRADELN2019_307455,1,1,8.3,NaN,NaN,0.045815,"LINESTRING (10.14211 53.56414, 10.14258 53.56409)"

In [6]:
hamburg_sr_raw_gdf.to_postgis("hamburg_sr_rad_2019_raw", engine, if_exists="replace")